name       : exo
version    : 4.18.0
release    : 2
source     :
    - https://archive.xfce.org/src/xfce/exo/4.18/exo-4.18.0.tar.bz2 : 4f2c61d045a888cdb64297fd0ae20cc23da9b97ffb82562ed12806ed21da7d55
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.xfce
summary    : Application library for the Xfce desktop environment.
description: |
    Application library for the Xfce desktop environment.
builddeps  :
    - pkgconfig(libxfce4ui-2)
setup      : |
    %configure --disable-debug
build      : |
    %make
install    : |
    %make_install
